server:
  port: 0


spring:
  application:
    name: user-details-service

#    h2:
#      console:
#        enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/keycloak?serverTimezone=UTC
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    #dialect:

  jpa:
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        ddl-auto: update
        #dialect: mil.af.kr.madhatter.debrief.config.persistence.OidToByteaPostgreSQLDialect
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        generate_statistics: false
        order_inserts: true
        show_sql: false
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: true
          time_zone: UTC

